datastaging:
  image: muccg/debian8-base
  volumes:
    - ./data:/data

dbstaging:
  extends:
    file: docker-compose-common.yml
    service: db

cachestaging:
  extends:
    file: docker-compose-common.yml
    service: cache

mongostaging:
  extends:
    file: docker-compose-common.yml
    service: mongo

uwsgistaging:
  image: muccg/rdrf:next_release
  command: uwsgi
  environment:
    - DJANGO_SETTINGS_MODULE=rdrf.settings
    - DBSERVER=dbstaging
    - DBUSER=rdrfapp
    - CACHESERVER=cachestaging
    - MONGOSERVER=mongostaging
    - WAIT_FOR_DB=1
    - WAIT_FOR_CACHE=1
    - WAIT_FOR_MONGO=1
  volumes_from:
    - datastaging
  ports:
    - "9300:9100"
    - "9301:9101"
  links:
    - dbstaging
    - cachestaging
    - mongostaging
